### ISSUE TITLE
Forgot to change address network bytes.

### ISSUE THREAD

**Issue by Crypto2** [ILCoinDevTeam/ilcoin-master#2]
It looks like you accidentally forgot to change the network version bytes at https://github.com/ILCoinDevTeam/ilcoin-master/blob/master/src/chainparams.cpp#L112 so they are still the same as Bitcoin's.

**Comment by ILCoinDevTeam** [comment]
Hi, we do not forgot we are like this same as Bitcoin because is the way we wanted to be. Regards!

**Comment by Crypto2** [comment]
You know this is going to cause endless problems for any exchange or wallet provider that lists you, right? With users sending to the wrong chain then either the funds having to be recovered or the users losing them depending on their policies.
